name              "aws-proftpd"
maintainer        "Kinesis Pty Ltd"
maintainer_email  "devs@kinesis.org"
license           "Apache 2.0"
description       "Installs proftpd"
version           "1.0.0"
recipe            "proftpd", "Installs proftpd backed by a SQL database"

supports "ubuntu"

depends "apt"
depends "aws"
depends "hostsfile"
depends "openssh"
depends "iptables"
depends "rsyslog"
depends "logrotate"
